version: '3.8'
services:
  bitsong:
    image: bzone/bitsong:v0.11.0
    hostname: bitsong
    build:
      context: .
      dockerfile: Dockerfile.bitsong
    volumes:
      - ./bitsong:/bitsong/.bitsongd/
      - ./scripts/bitsong/setup.sh:/bitsong/setup.sh
    entrypoint:
      - /bitsong/setup.sh
    ports:
      - 26657:26657
      - 1317:1317
      - 9090:9090
      - 9091:9091
  osmosis:
    image: bzone/osmosis:v12.1.0
    hostname: osmosis
    build:
      context: .
      dockerfile: Dockerfile.osmosis
    volumes:
      - ./osmosis:/osmosis/.osmosisd/
      - ./scripts/osmosis/setup.sh:/osmosis/setup.sh
    entrypoint:
      - /osmosis/setup.sh
    ports:
      - 27657:26657
      - 1417:1317
      - 9190:9090
      - 9191:9091