version: '3.8'
services:
  bitsong:
    image: bzone/bitsong:v0.11.0
    hostname: bitsong
    user: $UID:$GID
    build:
      context: .
      dockerfile: Dockerfile.bitsong
    volumes:
      - ./bitsong:/bitsong/.bitsongd
    command:
      - bitsongd
      - start
    ports:
      - 26657:26657
      - 1317:1317
  osmosis:
    image: bzone/osmosis:v12.1.0
    hostname: osmosis
    user: $UID:$GID
    build:
      context: .
      dockerfile: Dockerfile.osmosis
    volumes:
      - ./osmosis:/osmosis/.osmosisd
    command:
      - osmosisd
      - start
    ports:
      - 26757:26657
      - 1327:1317