[global]

# Specify the verbosity for the relayer logging output. Default: 'info'
# Valid options are 'error', 'warn', 'info', 'debug', 'trace'.
log_level = 'debug'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = true

[mode.channels]
enabled = true

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = false

[rest]
enabled = true
host = '0.0.0.0'
port = 3000

[telemetry]
enabled = false
host = '0.0.0.0'
port = 3001

[[chains]]
id = 'bitsong'
rpc_addr = 'http://bitsong:26657'
grpc_addr = 'http://bitsong:9090'
websocket_addr = 'ws://bitsong:26657/websocket'
rpc_timeout = '10s'
account_prefix = 'bitsong'
key_name = 'testkey'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 100000
max_gas = 5000000
gas_price = { price = 0.000000, denom = 'ubtsg' }
gas_multiplier = 1.5
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '10s'
trusting_period = '3minutes'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = ''

[[chains]]
id = 'osmosis'
rpc_addr = 'http://osmosis:26657'
grpc_addr = 'http://osmosis:9090'
websocket_addr = 'ws://osmosis:26657/websocket'
rpc_timeout = '10s'
account_prefix = 'osmo'
key_name = 'testkey'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 100000
max_gas = 3000000
gas_price = { price = 0.000, denom = 'uosmo' }
gas_multiplier = 1.5
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '10s'
trusting_period = '3minutes'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = ''