version: '3.8'
services:
  bitsong:
    image: bzone/bitsong:v0.11.0-wasm
    hostname: bitsong
    build:
      context: .
      dockerfile: Dockerfile.bitsong
    volumes:
      - ./bitsong:/bitsong/.bitsongd/
      - ./scripts/bitsong/setup.sh:/bitsong/setup.sh
    entrypoint:
      - /bitsong/setup.sh
    ports:
      - "26657:26657"
      - "1317:1317"
      - "9090:9090"
      - "9091:9091"